"""initial schema

Revision ID: 17656679fe18
Revises: 
Create Date: 2026-07-25 15:37:34.319357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '17656679fe18'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector is normally bootstrapped by the postgres init script
    # (backend/scripts/init-pgvector.sql); this makes the migration
    # self-sufficient against any Postgres target, not just our compose setup.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'PARTICIPANT', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('hackathons',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EVALUATING', 'FINALIZED', name='hackathon_status'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_submissions', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('criteria',
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=4, scale=3), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hackathon_participants',
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'user_id', name='uq_hackathon_user_participant')
    )
    op.create_table('hackathon_stats',
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=False),
    sa.Column('evaluations_completed', sa.Integer(), nullable=False),
    sa.Column('evaluations_in_progress', sa.Integer(), nullable=False),
    sa.Column('evaluations_queued', sa.Integer(), nullable=False),
    sa.Column('evaluations_failed', sa.Integer(), nullable=False),
    sa.Column('score_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tech_stack_frequency', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avg_score', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('top5_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id')
    )
    op.create_table('submissions',
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_url', sa.String(length=500), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=True),
    sa.Column('repo_description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLONING', 'ANALYZING', 'EVALUATING', 'COMPLETED', 'FAILED', name='submission_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clone_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analysis_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluation_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hackathon_id', 'user_id', name='uq_hackathon_user_submission')
    )
    op.create_index(op.f('ix_submissions_hackathon_id'), 'submissions', ['hackathon_id'], unique=False)
    op.create_index('ix_submissions_hackathon_status', 'submissions', ['hackathon_id', 'status'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'DEGRADED', name='evaluation_status'), nullable=False),
    sa.Column('final_score', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agents_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agents_abstained', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_submission_id'), 'evaluations', ['submission_id'], unique=True)
    op.create_table('rankings',
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('percentile', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('normalized_score', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('finalized', sa.Boolean(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.UUID(), nullable=True),
    sa.Column('computation_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hackathon_id'], ['hackathons.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_hackathon_id'), 'rankings', ['hackathon_id'], unique=False)
    op.create_index('ix_rankings_hackathon_rank', 'rankings', ['hackathon_id', 'rank'], unique=False)
    op.create_index(op.f('ix_rankings_rank'), 'rankings', ['rank'], unique=False)
    op.create_table('repo_embeddings',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('chunk_type', sa.String(length=100), nullable=True),
    sa.Column('chunk_content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_repo_embeddings_embedding_hnsw', 'repo_embeddings', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_repo_embeddings_submission_id'), 'repo_embeddings', ['submission_id'], unique=False)
    op.create_table('agent_results',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.String(length=100), nullable=False),
    sa.Column('criterion_id', sa.UUID(), nullable=True),
    sa.Column('score_raw', sa.DECIMAL(precision=6, scale=3), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('top_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('abstained', sa.Boolean(), nullable=False),
    sa.Column('abstain_reason', sa.Text(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_results_agent_id'), 'agent_results', ['agent_id'], unique=False)
    op.create_index('ix_agent_results_evaluation_agent', 'agent_results', ['evaluation_id', 'agent_id'], unique=False)
    op.create_index(op.f('ix_agent_results_evaluation_id'), 'agent_results', ['evaluation_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_agent_results_evaluation_id'), table_name='agent_results')
    op.drop_index('ix_agent_results_evaluation_agent', table_name='agent_results')
    op.drop_index(op.f('ix_agent_results_agent_id'), table_name='agent_results')
    op.drop_table('agent_results')
    op.drop_index(op.f('ix_repo_embeddings_submission_id'), table_name='repo_embeddings')
    op.drop_index('ix_repo_embeddings_embedding_hnsw', table_name='repo_embeddings', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('repo_embeddings')
    op.drop_index(op.f('ix_rankings_rank'), table_name='rankings')
    op.drop_index('ix_rankings_hackathon_rank', table_name='rankings')
    op.drop_index(op.f('ix_rankings_hackathon_id'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index(op.f('ix_evaluations_submission_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index('ix_submissions_hackathon_status', table_name='submissions')
    op.drop_index(op.f('ix_submissions_hackathon_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_table('hackathon_stats')
    op.drop_table('hackathon_participants')
    op.drop_table('criteria')
    op.drop_table('hackathons')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
