"""Server-side PDF export of an evaluation report (spec Section 10) via
weasyprint. A self-contained HTML+CSS string is built directly rather than
via a Jinja2 template file — the report has one fixed shape and pulling in a
templating layer for a single document adds indirection without benefit."""

import html
from datetime import datetime

from weasyprint import HTML

_CSS = """
@page { size: A4; margin: 2cm; }
body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #111; font-size: 11pt; }
h1 { color: #1d4ed8; font-size: 20pt; margin-bottom: 0; }
h2 { font-size: 14pt; border-bottom: 1px solid #ddd; padding-bottom: 4px; margin-top: 24px; }
.subtitle { color: #666; margin-top: 4px; }
.score-hero { font-size: 36pt; font-weight: bold; color: #1d4ed8; margin: 12px 0; }
.badge { display: inline-block; padding: 2px 10px; border-radius: 10px; font-size: 9pt; font-weight: bold; }
.badge-degraded { background: #fef3c7; color: #92400e; }
.badge-ok { background: #dcfce7; color: #166534; }
table { width: 100%; border-collapse: collapse; margin: 8px 0; }
th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #eee; font-size: 10pt; }
th { background: #f3f4f6; }
.evidence-item { margin: 4px 0; padding-left: 12px; border-left: 2px solid #93c5fd; font-size: 9.5pt; }
ul { margin: 4px 0; padding-left: 20px; }
footer { position: fixed; bottom: -1.5cm; font-size: 8pt; color: #999; }
"""


def _e(value) -> str:
    return html.escape(str(value)) if value is not None else ""


def _criterion_rows(by_criterion: list[dict]) -> str:
    return "".join(
        f"<tr><td>{_e(c['criterion'])}</td><td>{c['score']:.1f}</td>"
        f"<td>{c['weight'] * 100:.0f}%</td></tr>"
        for c in by_criterion
    )


def _agent_section(agent: dict) -> str:
    evidence_html = "".join(
        f'<div class="evidence-item"><strong>{_e(e.get("finding"))}</strong><br>{_e(e.get("impact"))}</div>'
        for e in agent.get("evidence", [])[:5]
    )
    abstained_note = (
        f'<p><span class="badge badge-degraded">Fallback scoring</span> {_e(agent.get("abstain_reason"))}</p>'
        if agent.get("abstained") or agent.get("fallback_used")
        else ""
    )
    return f"""
    <h2>{_e(agent['agent_id'].replace('_', ' ').title())} — {agent['score_raw']:.1f}/100</h2>
    {abstained_note}
    <p>{_e(agent.get('reasoning', ''))}</p>
    {evidence_html}
    """


def render_evaluation_pdf(*, report: dict, repo_name: str, participant_name: str, final_score: float | None) -> bytes:
    degraded = report.get("degraded", False)
    badge = (
        '<span class="badge badge-degraded">Degraded — static analysis only</span>'
        if degraded
        else '<span class="badge badge-ok">Complete</span>'
    )
    score_display = f"{final_score:.1f}" if final_score is not None else "N/A"

    agent_sections = "".join(_agent_section(a) for a in report.get("agent_results", []))
    strengths = "".join(f"<li>{_e(s)}</li>" for s in report.get("strengths", []))
    weaknesses = "".join(f"<li>{_e(w)}</li>" for w in report.get("weaknesses", []))

    html_doc = f"""
    <html>
    <head><meta charset="utf-8"><style>{_CSS}</style></head>
    <body>
        <h1>EVALON Evaluation Report</h1>
        <p class="subtitle">{_e(repo_name)} — submitted by {_e(participant_name)}</p>
        <div class="score-hero">{score_display}<span style="font-size:14pt;color:#666;">/100</span></div>
        {badge}
        <p>{_e(report.get('summary', ''))}</p>

        <h2>Scores by Criterion</h2>
        <table>
            <tr><th>Criterion</th><th>Score</th><th>Weight</th></tr>
            {_criterion_rows(report.get('scores', {}).get('by_criterion', []))}
        </table>

        <h2>Strengths</h2>
        <ul>{strengths or '<li>None recorded</li>'}</ul>

        <h2>Weaknesses</h2>
        <ul>{weaknesses or '<li>None recorded</li>'}</ul>

        {agent_sections}

        <footer>Generated by EVALON on {datetime.now().strftime('%Y-%m-%d %H:%M')} UTC</footer>
    </body>
    </html>
    """
    return HTML(string=html_doc).write_pdf()
